language: julia

#install:

os:
  - osx

julia:
  - 1.5

notifications:
  email: false

script:
  - julia -e 'using Pkg; Pkg.add("Conda"); using PyCall;
      pyimport_conda("sympy", "sympy")'
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build();
      Pkg.activate("."); Pkg.test("IBZ", coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage;
      Coveralls.submit(process_folder())'
  - julia --project ./docs/make.jl
coveralls: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
